# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A simple example for for NLOPT integration for RcppArmadillo
#'
#' @title NLOPT Integration Example
#' @return A numeric vector with two elements
#' @examples
#' test_nlopt_c()
#' @export
test_nlopt_c <- function() {
    .Call('_nloptC_test_nlopt_c', PACKAGE = 'nloptC')
}

