# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A simple example for NLOPT integration for RcppArmadillo
#'
#' @title NLOPT Integration Example
#' @return A numeric value
#' @examples
#' test_nlopt_cpp()
#' @export
test_nlopt_cpp <- function() {
    .Call('_nloptCpp_test_nlopt_cpp', PACKAGE = 'nloptCpp')
}

